[build]
publish = "public"
command = "hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.70.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b https://nice-privacy.netlify.app"

[context.deploy-preview.environment]
HUGO_VERSION = "0.70.0"

[context.branch-deploy]
command = "hugo --gc --minify -b https://nice-privacy.netlify.app"

[context.branch-deploy.environment]
HUGO_VERSION = "0.70.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

